
api_version = "2025-10"

[[extensions]]
name = "typ-osp-survey"
handle = "typ-osp-survey"
type = "ui_extension"
uid = "fddfc370-27c7-c30f-4ee0-a927194e2accadefd40c"
[[extensions.targeting]]
module = "./src/Checkout.jsx"
target = "purchase.thank-you.block.render"

