client_id = "2015ebb62d28424eacd5096814f3870d"
name = "productwidget"
application_url = "https://api.thegamified.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

[[webhooks.subscriptions]]
topics = [ "app/uninstalled" ]
uri = "/webhooks/app/uninstalled"

[[webhooks.subscriptions]]
topics = [ "app/scopes_update" ]
uri = "/webhooks/app/scopes_update"


[[webhooks.subscriptions]]
topics = [ "customers/data_request" ]
uri = "/webhooks/gdpr/data-request"

[[webhooks.subscriptions]]
topics = [ "customers/redact" ]
uri = "/webhooks/gdpr/customer-redact"

[[webhooks.subscriptions]]
topics = [ "shop/redact" ]
uri = "/webhooks/gdpr/shop-redact"


[access_scopes]
scopes = "write_products"

# âœ… REQUIRED BY SHOPIFY CLI (BUT HANDLED BY BACKEND)
[auth]
redirect_urls = [
  "https://api.thegamified.com/api/shopify/auth/callback"
]

[[extensions]]
type = "ui_extension"
name = "Thank You Page Link"
handle = "thankyou-link"
